/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoareasfigurasgeometricas;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author SENA
 */
public class FrmAreaTriangulo extends javax.swing.JFrame {

    /**
     * Creates new form FrmAreaTriangulo
     */
    public FrmAreaTriangulo() {
        initComponents();
        setLocationRelativeTo(this);
        getContentPane().setBackground(Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTriangulo = new javax.swing.JLabel();
        lblIngresarBase = new javax.swing.JLabel();
        lblIngresarAltura = new javax.swing.JLabel();
        txtBase = new javax.swing.JTextField();
        txtAltura = new javax.swing.JTextField();
        txtAreaTriangulo = new javax.swing.JTextField();
        btnBack3 = new javax.swing.JButton();
        btnAreaTriangulo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTriangulo.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblTriangulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTriangulo.setText("Área Triangulo");

        lblIngresarBase.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblIngresarBase.setForeground(new java.awt.Color(255, 255, 255));
        lblIngresarBase.setText("Ingresa el valor de la base:");

        lblIngresarAltura.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblIngresarAltura.setForeground(new java.awt.Color(255, 255, 255));
        lblIngresarAltura.setText("Ingresa el valor de la altura:");

        txtAreaTriangulo.setEditable(false);
        txtAreaTriangulo.setBackground(new java.awt.Color(255, 255, 255));
        txtAreaTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaTrianguloActionPerformed(evt);
            }
        });

        btnBack3.setBackground(new java.awt.Color(0, 0, 0));
        btnBack3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnBack3.setForeground(new java.awt.Color(255, 255, 255));
        btnBack3.setText("Back");
        btnBack3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack3ActionPerformed(evt);
            }
        });

        btnAreaTriangulo.setBackground(new java.awt.Color(0, 0, 0));
        btnAreaTriangulo.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnAreaTriangulo.setForeground(new java.awt.Color(255, 255, 255));
        btnAreaTriangulo.setText("ÁREA");
        btnAreaTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaTrianguloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(lblTriangulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblIngresarAltura)
                                    .addComponent(lblIngresarBase)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(txtAreaTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(btnAreaTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBase)
                            .addComponent(txtAltura, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack3)
                .addGap(3, 3, 3)
                .addComponent(lblTriangulo)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIngresarBase)
                    .addComponent(txtBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIngresarAltura)
                    .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnAreaTriangulo)
                .addGap(18, 18, 18)
                .addComponent(txtAreaTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        btnAreaTriangulo.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAreaTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaTrianguloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaTrianguloActionPerformed

    private void btnAreaTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaTrianguloActionPerformed
        // TODO add your handling code here:
        try {
            if (!txtBase.getText().isEmpty()){
                AreasFigurasGeometricas areaFigura = new AreasFigurasGeometricas();
                double base = Double.parseDouble(txtBase.getText());
                double altura = Double.parseDouble(txtAltura.getText());
                double resultado = areaFigura.areaTriangulo(base, altura);
                txtAreaTriangulo.setText(String.valueOf(resultado));
            }else{
                JOptionPane.showMessageDialog(null, "Falta ingresar un valor");
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Solo se puede ingresar valores númericos");
        }
    }//GEN-LAST:event_btnAreaTrianguloActionPerformed

    private void btnBack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBack3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAreaTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAreaTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAreaTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAreaTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAreaTriangulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAreaTriangulo;
    private javax.swing.JButton btnBack3;
    private javax.swing.JLabel lblIngresarAltura;
    private javax.swing.JLabel lblIngresarBase;
    private javax.swing.JLabel lblTriangulo;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtAreaTriangulo;
    private javax.swing.JTextField txtBase;
    // End of variables declaration//GEN-END:variables
}
